### ISSUE TITLE
Add basic initializer (e.g. track all transitions but dont track any actions) as default blueprint

### ISSUE THREAD

**Issue by avdeevs** [roundscope/ember-insights#38]
- [ ] The blueprint should be run automatically when addon is installed with the `ember install:addon` command;
- [x] Move mapping rules from README to the `config/../development` blueprint. Have a back links from README;
- [x] Move API usage documentation from README to the `initializers/__name__.js`.Have a back links from README;
- [x] `ember generate ember-insights-initializer <name>` (with default name, such as `<ember-insights>`);

**Comment by Zatvobor** [comment]
In addition, we should provide blueprint layout for mappings too. Let's say:

```javascript
import InsightsMappings from '../config/ember-insights'
//...
.track(InsightsMappings.production);
//...
```
